import { Inter } from "next/font/google";
import "./globals.css";
import ActiveLink from "@/app/comps/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ActiveLink href="/">HOME</ActiveLink> | <ActiveLink href="/fast">FAST</ActiveLink> | <ActiveLink href="/slow">SLOW</ActiveLink> 
          </nav>
          {children}</body>
    </html>
  );
}